### ISSUE TITLE
некорректная работа с групповыми раздачами на SteamCompanion

### ISSUE THREAD

**Issue by Zer0id** [KriBetko/KryBot#10]
![2](https://cloud.githubusercontent.com/assets/14043791/13580094/b69d36fc-e4b1-11e5-95c7-a51e75615200.png)

после нескольких циклов фарма бот пытается по несколько раз вступить в некоторые группы, причем в этих раздачах уже участвует.

после перезапуска программы проблемы нет

**Comment by KriBetko** [comment]
Сделал сообщения более понятными. Теперь их три типа: вступил, не вступил, уже состоит в группе.

А что по поводу того что пытается вступить в группу раздачи в которую уже вступил, так группы обычно несколько раздач создают. Потому так и выходит.

**Comment by Zer0id** [comment]
похоже, бот получает список групп в которых уже состоит только при первом запуске программы, и группы, в которые он уже вступил с момента запуска, не учитываются. потому в следующих циклах фарма он снова пытается в них вступить.
собственно потому и после перезапуска проблема исчезает

**Comment by KriBetko** [comment]
Бот не получает список групп. Если SteamCompanion считает что вы не вступили, то бот пытается в них вступить. 
Это лечится синхронизацией аккаунта SteamCompanion с аккаунтом Steam. Была идея после каждого цикла фарма синхронизировать, но из-за того что администратору SteamCompanion не хотелось чтобы его сервер "нагружали", отказались от идеи.
