### ISSUE TITLE
Не логинится на SG

### ISSUE THREAD

**Issue by kofe88** [KriBetko/KryBot#12]
Скачал версию 1.2.0.0 portable, открываю вкладку SG, далее логин, просит логин пароль от стима, ввожу, дальше переходит на страницу комьюнити стима, редиректа на SG нету, если окошко закрыть, то пишет "ошибка логина/сервера". В предыдущей версии 1.1.10.0 все ок.

**Comment by KriBetko** [comment]
А в новой версии как? Еще можно попробовать сбросить куки (Настройки - Удалить куки браузера).

**Comment by kofe88** [comment]
@KriBetko, в новой версии все хорошо, спасибо!)
