### ISSUE TITLE
Steamportal stopped entering GA.

### ISSUE THREAD

**Issue by InvictusX** [KriBetko/KryBot#13]
I set max entry fee to 5, 10 and even 20. It's not entering any giveaways anymore. 
Even the 0 points giveaways being ignored now.
Log displays no errors either.

Reserve points is set to 0.
  
```
[25.03.2016 16:24:26] {SteamPortal} Points: 19
[25.03.2016 16:24:29] {SteamPortal} Найдено подходящих раздач: 0
```

![screenshot](https://i.imgur.com/n8N8fkQ.png)

**Comment by KriBetko** [comment]
Fixed in 1.2.15 release. Thank you for reporting this issue.
