### ISSUE TITLE
Не растягивается окно черного списка

### ISSUE THREAD

**Issue by Zer0id** [KriBetko/KryBot#14]
![bl](https://cloud.githubusercontent.com/assets/14043791/14152973/7ac3e4c2-f6be-11e5-835b-6f48e5167508.png)

было бы еще замечательно, если б при добавлении подтягивалось название игры из магазина.
ну и сортировочку по ID/названию. хотя бы по ID пока что

**Comment by KriBetko** [comment]
В версии 1.3 Beta обновлен черный писок. В том числе он растягивается и можно его загрузить из аккаунта Steam.
