### ISSUE TITLE
не работает черный список на steamcompanion

### ISSUE THREAD

**Issue by Zer0id** [KriBetko/KryBot#15]
бот вступает в раздачи из черного списка

**Comment by KriBetko** [comment]
Пока что черный список отключен для SteamCompanion, чтобы не создавать избыточную нагрузку на сайт. Нагрузка связана с тем что id игры можно получить только на странице с раздачей - надо заходить на все страницы с раздачами, а их может быть много. 
Как только проблема решится, сразу включу.

**Comment by Zer0id** [comment]
да, в этом плане SG намного удобней.
я правильно понимаю, что если скрывать нежелательные игры посредством самого SG, то бот их и не увидит? и черный список где то еще работает?

**Comment by KriBetko** [comment]
Не увидит. 
Если не учитывать SteamCompanion, то работает на всех сайтах.

**Comment by Zer0id** [comment]
понятно, спасибо
