### ISSUE TITLE
Не авторизуется на gameminer.net

### ISSUE THREAD

**Issue by sharpblades** [KriBetko/KryBot#17]
не уверен что проблема бота, но с обычного браузера авторизуется без проблем
с браузера бота выдаётся неизвестная ошибка

**Comment by KriBetko** [comment]
Сделайте скриншот, так будет понятнее

**Comment by sharpblades** [comment]
лол, только что авторизовался, странно но более часа не мог, если проблема снова возникнет пришлю больше информации...
Так держать! отличная разработка! с первых призов отпраздную посылом донатного презента в качестве благодарности!
