### ISSUE TITLE
Help for instalation

### ISSUE THREAD

**Issue by Benamas** [KriBetko/KryBot#21]
How can i open it :/ i can't open it

**Comment by KriBetko** [comment]
What are you trying to run? If you can not run the installation version, try a portable. 
Minimum system requirements: Windows 7 and .NET Framework 4.5

**Comment by Benamas** [comment]
i try its no openig sir

**Comment by Benamas** [comment]
i use win10

**Comment by Benamas** [comment]
İts done thx
