### ISSUE TITLE
Бот вступает не во все раздачи на GameMiner и Playblink

### ISSUE THREAD

**Issue by Zer0id** [KriBetko/KryBot#26]
в черном списке этих игр нет. пробовал запустить без черного списка (переименовал его на время) - бот навступал в кучу раздач из черного списка, но в эти все равно не вступил.

![gm](https://cloud.githubusercontent.com/assets/14043791/15012947/26eb1ba6-1205-11e6-9565-bab2d5cb73e0.png)
Gameminer. на скрине видны две бесплатные раздачи внизу и одна дешевая сверху

![pb](https://cloud.githubusercontent.com/assets/14043791/15013035/ad4feaf0-1205-11e6-9b8a-515d44820d5e.png)
Playblink. видны две раздачи в которые можно вступить. серебряная медаль имеется - ниже видна раздача с серебряной медалью в которую бот вступил.
хоть эти две раздачи требуют ввода капчи (игры) в списке неподтвержденных их не было

**Comment by KriBetko** [comment]
Исправлено в версии 1.3.4

**Comment by Zer0id** [comment]
На Playblink проблема осталась. В этот раз обошел вниманием игры вообще без каких либо ограничений на вступление.
