### ISSUE TITLE
Не сохраняются общие настройки на версии 1.3.4.0 [bug]

### ISSUE THREAD

**Issue by aunderrednua** [KriBetko/KryBot#29]
На версии 1.3.4.0, собранной из исходников (Visual Studio Community 2015), не сохраняются настройки для вкладки "Общие". При перезапуске приложения слетают. Пробовал сохранять через "Сохранить" на вкладке и через "Сохранить" в верхнем меню. Если подкинуть заполненный profile.xml, он перетирается пустым при новом запуске приложения.

**Comment by KriBetko** [comment]
Исправлено в 1.3.5
