### ISSUE TITLE
Настройки для steamgifts.com: региональные раздачи и раздачи с несколькими копиями [enhancement]

### ISSUE THREAD

**Issue by aunderrednua** [KriBetko/KryBot#30]
Я попробовал добавить два новых пункта в настройки для steamgifts.com. 
1. Региональные раздачи - обычные раздачи, ограниченные регионом пользователя (как известно, в них всегда меньше вступивших, чем в остальных обычных, и шанс выигрыша намного больше).
2. Раздачи нескольких копий игр (с возможностью выбора количества копий) - часто встречаются раздачи 2-100 копий игр, можно выбрать минимальное количество копий (например, 5), начиная с которого бот будет вступать в раздачи (то есть, при выборе 5 бот вступит во все раздачи с 5, 6, 10, 50 и так далее копий). Обычно таких раздач не так много, поэтому очков хватает, даже если бот вступает во все такие раздачи.
Если это интересно, могу залить свои правки. 
Единственное, предупреждаю сразу, что к программированию не имею почти никакого отношения, сделал всё по аналогии с групповыми раздачами, но тестирование в течение двух дней багов не выявило, всё работает, мёрж с версией 1.3.4.0 прошёл успешно, хотя проверка кем-то, понимающим в программировании, не повредила бы.

**Comment by KriBetko** [comment]
Делайте свой Pull requests и посмотрим.

**Comment by KriBetko** [comment]
Спасибо за Pull request #32, он был принят.
