### ISSUE TITLE
Вишлист на Steamgifts, Steamcompanion

### ISSUE THREAD

**Issue by Zer0id** [KriBetko/KryBot#4]
не выводятся в логе сообщения о наличии/отсутствии раздач из вишлиста на Steamgifts, как это есть на steamcompanion

так же необходим по умолчанию приоритет этих раздач над максимальной ставкой, иначе смысла в этой опции мало. либо сделать опциональный чекбокс - игнорировать максимальную ставку.

**Comment by KriBetko** [comment]
Сообщения для SteamGifts исправлю. А что с приоритетом и максимальной ставкой? 

Сейчас раздачи из вишлиста загружаются первыми и в последствии первыми вступают, НО если к списку раздач применяется фильтр (цена, уровень и т.п.) то все идет вперемешку. Это чуть позже исправлю разделением обычные, групповые и вишлист раздачи на отдельные списки.

**Comment by Zer0id** [comment]
хотелось бы, чтоб было что то вроде этого:

если не менять интерфейс бота, то что бы с отмеченным чекбоксом wishlist бот сразу вступал в эти раздачи до применения фильтров. 
либо, как писал выше, сделать эту возможность опциональной
либо в дополнение к черному списку добавить белый список, для вступления в раздачи в первую очередь, игнорируя все фильтры

сейчас бот не вступает в раздачи из вишлиста, если их цена выше максимальной ставки.
вишлист сам по себе уже подразумевает желание получить данные игры больше чем остальные, а в сочетании с ограничением максимальной ставки получилось бы более гибко регулировать в какие раздачи вступать, а в какие нет

**Comment by lookerinside** [comment]
Хочу добавить к вишлисту на SC вступление в контрибьюторные раздачи. И сделать опцию выбора вступления в раздачи по времени, чтобы сначала вступало в те, которые раньше закончатся

**Comment by KriBetko** [comment]
Создавайте для каждой ошибки и предложения отдельную тему. Так будет удобнее мне и вам.

**Comment by Zer0id** [comment]
С появлением кнопки "не применять сортировку к виш листу" ничего не изменилось - что с галочкой, что без, бот находит раздачи из вишлиста:
[02.04.2016 12:37:22] {SteamCompanion} Найдено 4 раздач из вишлиста на 1 страницах
но не вступает в них, если они выше макс ставки
