### ISSUE TITLE
Steamcompanion crash

### ISSUE THREAD

**Issue by InvictusX** [KriBetko/KryBot#6]
Log:
> [06.03.2016 17:03:52] {SteamCompanion} Points: 1159
> [06.03.2016 17:03:53] {SteamCompanion} Найдено 5 раздач из вишлиста на 1 страницах
> [06.03.2016 17:03:56] {SteamCompanion} Найдено 126 групповых раздач на 7 страницах
> [06.03.2016 17:03:58] {SteamCompanion} Найдено подходящих раздач: 138

Error message:
```
System.NullReferenceException: Object reference not set to an instance of an object.
at KryBot.Parse.SteamCompanionGetJoinData(ScGiveaway giveaway, Bot bot)
at KryBot.Web.SteamCompanionloinGiveaway(Bot bot, ScGiveaway giveaway)
at KryBot.Web.<>c_DisplayClass9_0.<SteamCompanionloinGiveawayAsync>b_0()
```  
  
OS: W10Pro x64

**Comment by KriBetko** [comment]
Thank you for your message. I tried to fix it in version https://github.com/KriBetko/KryBot/releases/tag/1.2.0.0
