### ISSUE TITLE
Can't login to Steamcompanion or Usegamble

### ISSUE THREAD

**Issue by lib2k** [KriBetko/KryBot#65]
Trying to log into either of the two as usual, the window pops up, I'm already signed into Steamcommunity so I hit the big green "Sign in" button, the windows closes itself and the log says `Error login/server` for either of the two services.  

Tried with manually copy-pasting cookie data into the config and with a completely fresh config. No dice.

**Comment by VSMent** [comment]
The same for me(

**Comment by lib2k** [comment]
Both are gone, so this is a non-issue anymore I suppose.
Also GameMiner went out of business for good.
