### ISSUE TITLE
Вишлист на Steamcompanion

### ISSUE THREAD

**Issue by lookerinside** [KriBetko/KryBot#7]
Перенес сюда по просьбе.
Хочется видеть в SC вступление в контрибьюторные раздачи. 
И сделать опцию выбора вступления в раздачи по времени, чтобы сначала вступало в те, которые раньше закончатся

**Comment by KriBetko** [comment]
Вступление в контрибьюторские раздачи реализовано в 1.3 Beta. Сортировка по времени пока отложена.
